### PR TITLE
added editorconfig,CLI arguments and average score

### PR DESCRIPTION
**Pull request by ghost**
Hey, you said you'd appreciate PR's, so here is one :)
Its not perfect, but it improves the concept a little, I hope.

### CODE REVIEW

**Comment by ghost** [comment]
Just realized I've squeezed in a few bugs last minute, I hope you can fix those ;)

**Comment by poppinlp** [comment]
Sry, I just saw this. I'll take a look at it recently.


> Just realized I've squeezed in a few bugs last minute, I hope you can fix those ;)

By this, do you mean there are some bugs you've known already?

**Comment by ghost** [comment]
Just tried it again, seems all fine. Ready to merge :)

**Comment by niftylettuce** [comment]
👍

**Comment by poppinlp** [comment]
@GitGangGuy  Cool! Thanks.

**Pull request merged**
